# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: wice_grid_examples_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  database: wice_grid_examples_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: wice_grid_examples_production
  username: 
  password: 
  host: localhost
